trigger:
  branches:
    include:
      - main
  paths:
    include:
      - classify/*

stages:
  - stage: BuildClassify
    displayName: Build Classify image
    jobs:
      - job: BuildClassify
        displayName: Build Classify
        pool:
          name: "Azure Pipelines"
        steps:
          - task: AzureKeyVault@2
            inputs:
              azureSubscription: "vault connection"
              KeyVaultName: "WhoThisActorSecrets"
              SecretsFilter: "*"
              RunAsPreJob: true
          - task: Docker@2
            inputs:
              containerRegistry: "whothisactorRegistry"
              repository: "whothisactor-classify"
              command: "build"
              Dockerfile: "classify/Dockerfile"
              arguments: "--platform linux/amd64 --build-arg CONNECTIONSTRING=$(CONNECTIONSTRING)"

          - task: Docker@2
            inputs:
              containerRegistry: "whothisactorRegistry"
              repository: "whothisactor-classify"
              command: "push"
  - stage: Deploy
    displayName: Deploy CLASSIFY
    jobs:
      - job: DeployClassify
        displayName: DeployClassify
        pool:
          name: "Azure Pipelines"
        steps:
          - task: AzureRmWebAppDeployment@5
            inputs:
              ConnectionType: "AzureRM"
              azureSubscription: "Azure for Students(ef7f1a56-77e4-4ff0-81f5-ecf53df6ab4b)"
              appType: "webAppContainer"
              WebAppName: "whothisactor-classify"
              DockerNamespace: "whothisactorcontainers.azurecr.io"
              DockerRepository: "whothisactor-classify"
              DockerImageTag: "$(Build.BuildId)"
