trigger:
  branches:
    include:
      - main
  paths:
    include:
      - api/*

resources:
  - repo: self

variables:
  tag: "$(Build.BuildId)"

stages:
  - stage: BuildApi
    displayName: Build API image
    jobs:
      - job: BuildApi
        displayName: Build API
        pool:
          name: "Azure Pipelines"
        steps:
          - task: AzureKeyVault@2
            inputs:
              azureSubscription: 'vault connection'
              KeyVaultName: 'WhoThisActorSecrets'
              SecretsFilter: '*'
              RunAsPreJob: true
          - task: Docker@2
            inputs:
              containerRegistry: 'whothisactorRegistry'
              repository: 'whothisactor-api'
              command: 'build'
              Dockerfile: 'api/Dockerfile'
              arguments: '--platform linux/amd64 --build-arg CONNECTIONSTRING=$(CONNECTIONSTRING) --build-arg SENHAKEYSTORE=$(SENHAKEYSTORE) --build-arg TMDBAPIKEY=$(TMDBAPIKEY) --build-arg DBPASSWORD=$(DBPASSWORD) --build-arg CLASSIFYADDRESS=$(CLASSIFYADDRESS)'

          - task: Docker@2
            inputs:
              containerRegistry: 'whothisactorRegistry'
              repository: 'whothisactor-api'
              command: 'push'
          - task: AzureRmWebAppDeployment@5
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Azure for Students(ef7f1a56-77e4-4ff0-81f5-ecf53df6ab4b)'
              appType: 'webAppContainer'
              WebAppName: 'whothisactor-api'
              DockerNamespace: 'whothisactorRegistry'
              DockerRepository: 'whothisactor-api'