trigger:
  branches:
    include:
      - main
  paths:
    include:
      - classify/*

stages:
  - stage: BuildClassify
    displayName: Build Classify image
    jobs:
      - job: BuildClassify
        displayName: Build Classify
        pool:
          name: "Azure Pipelines"
        steps:
          - checkout: self
            lfs: true
          - task: AzureKeyVault@2
            inputs:
              azureSubscription: "vault connection"
              KeyVaultName: "WhoThisActorSecrets"
              SecretsFilter: "*"
              RunAsPreJob: true
          - task: Docker@2
            inputs:
              containerRegistry: "whothisactorRegistry"
              repository: "whothisactor-classify"
              command: "build"
              Dockerfile: "classify/Dockerfile"
              tags: "who"
              arguments: "--platform linux/amd64 --build-arg CONNECTIONSTRING=$(CONNECTIONSTRING)"
          - task: Docker@2
            inputs:
              containerRegistry: "whothisactorRegistry"
              repository: "whothisactor-classify"
              tags: "who"
              command: "push"
  - stage: Deploy
    displayName: Deploy Classify
    jobs:
      - job: DeployClassify
        displayName: DeployClassify
        pool:
          name: "Azure Pipelines"
        steps:
          - task: AzureContainerApps@1
            inputs:
              azureSubscription: "Azure for Students(ef7f1a56-77e4-4ff0-81f5-ecf53df6ab4b)"
              containerAppName: "classify"
              resourceGroup: "WhoThisActorStudent"
              imageToDeploy: "whothisactorcontainers.azurecr.io/whothisactor-classify:who"
