trigger:
  branches:
    include:
      - main
  paths:
    include:
      - api/*

# Novo trigger para a pasta classify
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - classify/*

resources:
  - repo: self

variables:
  tag: "$(Build.BuildId)"

stages:
  - stage: BuildApi
    displayName: Build API image
    # Condição para não rodar o stage BuildApi se o trigger for para classify
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'), not(contains(variables['Build.TriggeredBy'], 'classify')))
    jobs:
      - job: BuildApi
        displayName: Build API
        pool:
          name: "Azure Pipelines"
        steps:
          - task: AzureKeyVault@2
            inputs:
              azureSubscription: "serviceconnection"
              KeyVaultName: "WhoThisActorVault"
              SecretsFilter: "*"
              RunAsPreJob: true

          - task: Docker@2
            inputs:
              containerRegistry: "whothisactor"
              repository: "whoThisActorApi"
              command: "build"
              Dockerfile: "api/Dockerfile"
              tags: "latest"
              arguments: >
                --platform linux/amd64 
                --build-arg CONNECTIONSTRING=$(CONNECTIONSTRING)
                --build-arg SENHAKEYSTORE=$(SENHAKEYSTORE)
                --build-arg TMDBAPIKEY=$(TMDBAPIKEY)
                --build-arg DBPASSWORD=$(DBPASSWORD)
                --build-arg CLASSIFYADDRESS=$(CLASSIFYADDRESS)

          - task: Docker@2
            inputs:
              containerRegistry: "whothisactor"
              repository: "whoThisActorApi"
              command: "push"
              tags: "latest"

  - stage: BuildClassify
    displayName: Build Classify image
    # Condição para não rodar o stage BuildClassify se o trigger for para api
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'), not(contains(variables['Build.TriggeredBy'], 'api')))
    jobs:
      - job: BuildClassify
        displayName: Build Classify
        pool:
          name: "Azure Pipelines"
        steps:
          - task: AzureKeyVault@2
            inputs:
              azureSubscription: "serviceconnection"
              KeyVaultName: "WhoThisActorVault"
              SecretsFilter: "*"
              RunAsPreJob: true

          - task: Docker@2
            inputs:
              containerRegistry: "whothisactor"
              repository: "whothisactor-classify-api"
              command: "build"
              Dockerfile: "classify/Dockerfile"
              tags: "latest"
              arguments: >
                --platform linux/amd64 
                --build-arg CONNECTIONSTRING=$(CONNECTIONSTRING)
                --build-arg SENHAKEYSTORE=$(SENHAKEYSTORE)
                --build-arg TMDBAPIKEY=$(TMDBAPIKEY)
                --build-arg DBPASSWORD=$(DBPASSWORD)
                --build-arg CLASSIFYADDRESS=$(CLASSIFYADDRESS)

          - task: Docker@2
            inputs:
              containerRegistry: "whothisactor"
              repository: "whothisactor-classify-api"
              command: "push"
              tags: "latest"