name: Trigger auto deployment for whothisactor-classify-api

on:
  push:
    branches: [main]
    paths:
      - "classify/**"
      - ".github/workflows/whothisactor-classify-api-AutoDeployTrigger-fe6266b6-b9dc-4314-9a1d-8c33a0615807.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.WHOTHISACTORCLASSIFYAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WHOTHISACTORCLASSIFYAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WHOTHISACTORCLASSIFYAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Decode connection string and save to a file
        run: |
          echo "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" | base64 --decode > connection_string.txt

      - name: Build and push container image to registry
        uses: azure/docker-login@v1
        with:
          login-server: whothisactor.azurecr.io
          username: ${{ secrets.WHOTHISACTORCLASSIFYAPI_REGISTRY_USERNAME }}
          password: ${{ secrets.WHOTHISACTORCLASSIFYAPI_REGISTRY_PASSWORD }}

      - name: Build and push image
        run: |
          docker build -t whothisactor.azurecr.io/whothisactor-classify-api:${{ github.sha }} --build-arg CONNECTIONSTRING=${{ secrets.CONNECTIONSTRING }} classify
          docker push whothisactor.azurecr.io/whothisactor-classify-api:${{ github.sha }}
