name: Trigger auto deployment for whothisactor-classify-api

on:
  push:
    branches: [main]
    paths:
      - "classify/**"
      - ".github/workflows/whothisactor-classify-api-AutoDeployTrigger-fe6266b6-b9dc-4314-9a1d-8c33a0615807.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.WHOTHISACTORCLASSIFYAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WHOTHISACTORCLASSIFYAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WHOTHISACTORCLASSIFYAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Decode connection string and save to a file
        run: |
          echo "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" | base64 --decode > connection_string.txt

      - name: Download Blob
        run: |
          CONNECTION_STRING=$(cat connection_string.txt)
          az storage blob download \
            --container-name containerblob \
            --name embeddings_combinados.pkl \
            --file embeddings_combinados.pkl \
            --connection-string "$CONNECTION_STRING"
            
          # Mover o arquivo para a pasta correta
          mv embeddings_combinados.pkl classify/embeddings_combinados.pkl

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/classify
          registryUrl: whothisactor.azurecr.io
          registryUsername: ${{ secrets.WHOTHISACTORCLASSIFYAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WHOTHISACTORCLASSIFYAPI_REGISTRY_PASSWORD }}
          containerAppName: whothisactor-classify-api
          resourceGroup: WhoThisActorGroup
          imageToBuild: whothisactor.azurecr.io/whothisactor-classify-api:${{ github.sha }}
          buildArguments: |
            CONNECTIONSTRING=${{ secrets.CONNECTIONSTRING }}
